# Generated by Django 4.2.5 on 2023-09-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
    ]
