# Generated by Django 4.2.5 on 2023-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_energydata_added_alter_energydata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='impact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='pestle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='sector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='start_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
